#!/usr/bin/env python

import metadata
import yaml

with open('public/metadata.md', 'w') as md:
    md.write('---\n')
    yaml.dump(
        {
            'project_name': metadata.project_name,
            'git_hash_sha': metadata.git_hash_sha,
            'slogan':metadata.slogan,
            'sales_pitch': metadata.sales_pitch
        },
        md
    )
    md.write('---\n')
    
    md.write(f'This file was generated by {__file__}.')
