#!/usr/bin/env python

import metadata
import yaml

with open('gen/metadata.md', 'w') as md:
    md.write('---\n')
    yaml.dump(
        {
            'project_name': metadata.project_name,
            'git_hash_sha': metadata.git_hash_sha,
            'basic_idea': metadata.basic_idea
        },
        md
    )
    md.write('---\n')
    
    md.write(f'This file was generated by {__file__}.')
